# Site settings
title: Luwei Ying
email: luwei.ying@wustl.edu
description: > # this means to ignore newlines until "baseurl:"
  Ph.D. Candidate, Political Science, WUSTL.
  
  Incoming Assistant Professor, Political Science, UCLA
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "Luwei-Ying.github.io" # the base hostname & protocol for your site
github_username:  Luwei-Ying

permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap
  
# Build settings
markdown: kramdown
theme: minima
